# Generated by Django 4.1.7 on 2023-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_us",
            field=models.TextField(blank=True, null=True, verbose_name="О себе."),
        ),
    ]
