# Generated by Django 4.1.7 on 2023-03-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_article",
                    models.CharField(max_length=75, verbose_name="Название статьи"),
                ),
                ("text_article", models.TextField(verbose_name="Статья")),
                ("date_publish", models.DateTimeField(verbose_name="Дата публикации")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.CreateModel(
            name="section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(max_length=50, verbose_name="Название раздела"),
                ),
            ],
            options={
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
        migrations.CreateModel(
            name="photo_for_article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.ImageField(upload_to="photoForArticle")),
                (
                    "id_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.article"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=50, verbose_name="Имя автора"),
                ),
                (
                    "comment_text",
                    models.TextField(max_length=200, verbose_name="Текст комментария"),
                ),
                (
                    "article_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.article"
                    ),
                ),
            ],
            options={
                "verbose_name": "Коментарий",
                "verbose_name_plural": "Коментарии",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="section_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="blogs.section",
            ),
        ),
    ]
