# Generated by Django 4.1.7 on 2023-05-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель комментария'),
        ),
        migrations.AddField(
            model_name='article',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель статьи'),
        ),
    ]
