# Generated by Django 4.1.4 on 2022-12-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_section_comment_article_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='topic_name',
            new_name='section_name',
        ),
    ]
